language: bash

services:
- docker

env:
  global:
  - BASE_IMAGE_STABILITY_TAG=2.4.5
  - ALPINE_VER=3.10
  matrix:
  - VARNISH_VER=6.0.6 TAGS=6.0,6,latest
  - VARNISH_VER=4.1.11 TAGS=4.1,4

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
